fetch_wit_deps:
    wkg wit fetch

build: fetch_wit_deps
    wash build --skip-fetch

integration-test: fetch_wit_deps
    cargo test --test '*'

test: fetch_wit_deps
    cargo test --lib --bins

lint: fetch_wit_deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
