
build:
    wash build

unit-test:
    wash wit deps
    cargo test --lib --bins

integration-test:
    wash wit deps
    cargo test --test '*'

test: unit-test && integration-test

lint:
    wash wit deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
