name ="crud-component"
language = "rust"
type = "component"

[component]
wit_world = "component"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:data-api/data-api"
source = "file://../wit/world.wit"
