package betty-blocks-utilities:upload-file@2.0.0;

// Our platform passes the property as [{ kind: "FILE", name: "<propertyName>" }], we have to accommodate that in the store interfaces.

interface upload-file {
    use betty-blocks-utilities:data-api/data-api.{helper-context};
    use betty-blocks-utilities:types/types@2.0.0.{betty-model, betty-property};

    record upload-result {
        reference: string,
        file-size: u64,
        message: option<string>,
    }

    record input {
        model: betty-model,
        property: betty-property,
        file-bytes: list<u8>,
        full-filename: string,
    }

    upload: func(
        helper-context: helper-context,
        input: input,
    ) -> result<upload-result, string>;
}

world upload {
    import wasi:http/outgoing-handler@0.2.0;
    import betty-blocks-utilities:data-api/data-api;
    import betty-blocks-utilities:types/types@2.0.0;

    export upload-file;
}
