package betty-blocks-types:crud@4.0.0;

interface crud {
    use betty-blocks-types:data-api/data-api@3.0.0.{data-api};
    use betty-blocks-types:types/types@3.0.0.{betty-model, betty-property-mapping, betty-property, betty-record-json};

    create: func(data-api: borrow<data-api>, model: betty-model, mapping: betty-property-mapping, validation-sets: option<list<string>>) -> result<betty-record-json, string>;
    update: func(data-api: borrow<data-api>, model: betty-model, record-id: string, mapping: betty-property-mapping, validation-sets: option<list<string>>) -> result<betty-record-json, string>;
    upsert: func(data-api: borrow<data-api>, model: betty-model, mapping: betty-property-mapping, unique-by: betty-property, validation-sets: option<list<string>>) -> result<betty-record-json, string>;
    delete: func(data-api: borrow<data-api>, model: betty-model, record-id: string) -> result<string, string>;
}
