fetch_wit_deps:
    wkg wit fetch

build: fetch_wit_deps
    wash build --skip-fetch

test:
    cargo test --lib --bins

integration-test:
    cargo test --test integration_test_mcp -- --nocapture

lint: fetch_wit_deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
