
build:
    wash build

test:
    cargo test --lib --bins

integration-test:
    cargo test --test integration_test_mcp -- --nocapture

lint:
    wash wit deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
