set allow-duplicate-recipes := true
import '../../wit-deps.just'

fetch-wit-deps: wkg-fetch
    cd ../utilities/auth && just fetch-wit-deps

build: fetch-wit-deps
    wash build --skip-fetch

test:
    cargo test --lib --bins

integration-test:
    cargo test --test integration_test_mcp -- --nocapture

lint: fetch-wit-deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
