name = "data-api-test-component"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:data-api/data-api"
source = "file://../wit/world.wit"
