apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: native
  annotations:
    description: betty blocks native app which contains the providers and components to connect to the betty blocks platform
    version: v{{VERSION}}
    experimental.wasmcloud.dev/shared: 'true'
spec:
  components:
    - name: http-wrapper
      # placeholder for the http server to link to (for kubernetes)
      type: component
      properties:
        image: "{{REGISTRY}}/http-wrapper:{{VERSION}}"
      traits:
        - type: daemonscaler
          properties:
            instances: 1
    - name: crud-component
      type: component
      properties:
        image: "{{REGISTRY}}/crud-component:{{VERSION}}"
      traits:
        - type: daemonscaler
          properties:
            instances: 1
        - type: link
          properties:
            target: data-api
            namespace: betty-blocks
            package: data-api
            interfaces: [data-api]
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        config:
        - name: http-config
          properties:
            routing_mode: 'path'
            default_address: '0.0.0.0:8080'
      traits:
        - type: daemonscaler
          properties:
            instances: 10
        - type: link
          properties:
            target: http-wrapper
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: path-native
                  properties:
                    address: '0.0.0.0:8080'
                    path: '/admin'
    - name: data-api
      type: capability
      properties:
        image: "{{REGISTRY}}/data-api:{{VERSION}}"
        config:
          - name: data-config
            properties:
              key-vault-target: "key-vault"
              jaws-issuer: "actions_js"
              jaws-secret-key: "DATA_RPC_ACTIONS_JS_SECRET"
              data-api-address: http://data-rpc.frontend.svc.cluster.local:50054
    - name: key-vault
      type: capability
      properties:
        image: "{{REGISTRY}}/key-vault:{{VERSION}}"
        id: "key-vault"
        config:
          - name: key-vault-config
            properties:
              endpoint: "{{KEYVAULT_ENDPOINT}}"
              key: actions-js-secrets
