name = "SMTP send mail component"
language = "rust"
type = "component"

[component]
wit_world = "component"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:smtp/client"
source = "file://../wit/world.wit"
