package betty-blocks:file;

// Our platform passes the property as [{ kind: "FILE", name: "<propertyName>" }], we have to accommodate that in the store interfaces.

interface upload-file {
    use betty-blocks:data-api/data-api.{helper-context};
    use betty-blocks:types/types.{model, property};

    record upload-result {
        reference: string,
        file-size: u64,
        message: option<string>,
    }

    upload: func(
        helper-context: helper-context,
        model: model,
        property: property,
        file-bytes: list<u8>,
        full-filename: string,
    ) -> result<upload-result, string>;
}

interface store {
    use betty-blocks:data-api/data-api.{helper-context};
    use betty-blocks:types/types.{model, property};

    store-file: func(helper-context: helper-context, model: model, property: list<property>, url: string) -> result<string, string>;
}

interface store-base64 {
    use betty-blocks:data-api/data-api.{helper-context};
    use betty-blocks:types/types.{model, property};

    store-file: func(helper-context: helper-context, model: model, property: list<property>, data: string, filename: string, file-extension: string) -> result<string, string>;
}
