package betty-blocks:file;

// Our platform passes the property as [{ kind: "FILE", name: "<propertyName>" }], we have to accommodate that in the store interfaces.

interface upload-file {
    use betty-blocks:data-api/data-api.{helper-context};
    use betty-blocks:types/types.{model, property};

    record upload-result {
        reference: string,
        file-size: u64,
        message: option<string>,
    }

    record input {
        model: model,
        property: property,
        file-bytes: list<u8>,
        full-filename: string,
    }

    upload: func(
        helper-context: helper-context,
        input: input,
    ) -> result<upload-result, string>;
}
