package betty-blocks-utilities:types;

interface types {
    type json-string = string;

    record betty-model {
        name: string
    }

    record betty-property {
        name: string,
    }

    record betty-property-path {
        name: string,
        kind: string,
        object-fields: option<list<betty-property>>
    }

    record betty-property-map {
        key: list<betty-property-path>,
        value: option<json-string>
    }

    type betty-property-mapping = list<betty-property-map>;
}
