

fetch_wit_deps:
  wkg wit fetch

build: fetch_wit_deps
  cargo build --release --target wasm32-wasip2

test:
    cargo test --lib --bins

integration-test:
    cargo test --tests '*'

lint:
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
