apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: http-wrapper
  annotations:
    version: v0.0.1
spec:
  components:
    - name: actions
      type: component
      properties:
        image: file://./build/actions.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]

    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.13.1

    - name: http-component
      type: component
      properties:
        image: file://./build/http_wrapper_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: actions
            namespace: betty-blocks
            package: types
            interfaces: [actions]

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
