name = "http-wrapper"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "main"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:types@0.1.0"
source = "file://./external/actions.wit"