[package]
name = "log-to-stdout"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1.41"
# tracing-logfmt = "0.3.5"
tracing-subscriber = "0.3.19"
wit-bindgen = "0.42.0"
