set allow-duplicate-recipes := true
import '../../wit-deps.just'

fetch-wit-deps: wkg-fetch
    cd test-component && {{ repo_root }}/scripts/generate-wkg-toml.sh && wkg wit fetch

build: fetch-wit-deps
    wash build --skip-fetch

test: fetch-wit-deps
    cargo test --lib --bins

integration-test: fetch-wit-deps
    cargo test --tests '*'

lint: fetch-wit-deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
