fetch-wit-deps:
    wkg wit fetch

build: fetch-wit-deps
    wash build --skip-fetch

integration-test: fetch-wit-deps
    cargo test --test '*'

test: fetch-wit-deps
    cargo test --lib --bins

lint: fetch-wit-deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
