name = "pdf-generator"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "provider"
wasm_target = "wasm32-wasip2"

[overrides]
"betty-blocks-utilities:data-api" = { path = "./../data-api/wit/world.wit" }
"betty-blocks-utilities:types" = { path = "./../../../wit/types.wit" }
