fetch_wit_deps:
    WKG_CONFIG_FILE={{justfile_directory()}}/../../../wkg.toml wash wit fetch

build: fetch_wit_deps
    wash build --skip-fetch

test:
    cargo test --lib --bins

integration-test:
    cargo test --tests '*'

lint: fetch_wit_deps
    cargo check

formatting *args:
    cargo fmt --all {{args}}

clippy:
    cargo clippy --all-targets --all-features -- -D warnings
