#!/usr/bin/env bash
#
# Generate the wkg.toml for the component or WIT package in the current directory.
#
# One rule decides where every betty-blocks-types dependency comes from: the local checkout
# when wit/<pkg> declares exactly the version being asked for, the registry otherwise.
#
#   asks @2.2.0, wit/types declares @2.2.0  ->  { path = "../../../wit/types" }
#   asks @2.2.0, wit/types declares @2.3.0  ->  registry, which still has 2.2.0
#
# Usage:
#   generate-wkg-toml.sh             write ./wkg.toml (or remove it when nothing needs a path)
#   generate-wkg-toml.sh --dry-run   print what would be written, touch nothing
#
# Run it from a component directory (one holding wit/world.wit) or from a wit/<pkg> directory.

set -uo pipefail

NAMESPACE="betty-blocks-types"
HEADER="# Generated by scripts/generate-wkg-toml.sh - do not edit, do not commit."

DRY_RUN=false
case "${1:-}" in
"") ;;
--dry-run) DRY_RUN=true ;;
*)
  echo "usage: generate-wkg-toml.sh [--dry-run]" >&2
  exit 2
  ;;
esac

declare -A required_version=()
declare -A resolved_from=() # path | registry
declare -A requesters=()    # every "<version> by <file>" seen, one per line

root=""
wit_files=()
conflicted=()

main() {
  find_repo_root
  find_wit_files
  resolve_dependencies
  check_for_conflicts
  report_decisions
  write_wkg_toml
}

find_repo_root() {
  root=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "::error::generate-wkg-toml.sh: not inside a git checkout" >&2
    exit 2
  }
}

find_wit_files() {
  local f
  shopt -s nullglob
  for f in wit/*.wit; do wit_files+=("$f"); done
  if [ "${#wit_files[@]}" -eq 0 ]; then
    for f in ./*.wit; do wit_files+=("$f"); done
  fi
  if [ "${#wit_files[@]}" -eq 0 ]; then
    echo "::error::generate-wkg-toml.sh: no .wit files in $(display "$PWD") or its wit/ directory" >&2
    exit 2
  fi
}

check_for_conflicts() {
  if [ "${#conflicted[@]}" -gt 0 ]; then
    report_conflicts
    exit 1
  fi
}

# A registry package carries its own dependencies, so it is never walked.
resolve_dependencies() {
  local queue=("${wit_files[@]}")
  local file pkg version local_dir local_version dep

  while [ "${#queue[@]}" -gt 0 ]; do
    file=${queue[0]}
    queue=("${queue[@]:1}")

    while read -r pkg version; do
      [ -n "$pkg" ] || continue

      if [ -n "${required_version[$pkg]:-}" ]; then
        [ "${required_version[$pkg]}" = "$version" ] || note_conflict "$pkg" "$version" "$file"
        continue
      fi

      required_version[$pkg]=$version
      requesters[$pkg]="$version by $(display "$file")"

      local_dir="$root/wit/$pkg"
      local_version=$(package_version "$local_dir")

      if [ "$local_version" = "$version" ]; then
        resolved_from[$pkg]=path
        for dep in "$local_dir"/*.wit; do
          [ -f "$dep" ] && queue+=("$dep")
        done
      else
        resolved_from[$pkg]=registry
      fi
    done < <(required_packages_in "$file")
  done
}

# One "<package> <version>" line per betty-blocks-types interface reference, from both
# `import ns:pkg/iface@X.Y.Z;` and `use ns:pkg/iface@X.Y.Z.{...}` -- the version pattern is
# semver-shaped so the `.` opening a use list is not swallowed. A `package ns:pkg@X.Y.Z;` line
# has no interface segment, so a package never overrides itself.
required_packages_in() {
  grep -ohE "$NAMESPACE:[a-z0-9-]+/[a-z0-9-]+@[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?" "$1" 2>/dev/null |
    sed -E "s|^$NAMESPACE:([a-z0-9-]+)/[a-z0-9-]+@|\1 |" |
    sort -u
}

package_version() {
  local dir=$1 wit found
  [ -d "$dir" ] || return 0
  shopt -s nullglob
  for wit in "$dir"/*.wit; do
    found=$(sed -nE "s/^package $NAMESPACE:[a-z0-9-]+@([^;[:space:]]+);.*/\1/p" "$wit" | head -1)
    if [ -n "$found" ]; then
      echo "$found"
      return 0
    fi
  done
}

# wkg wit fetch keeps only the first version it meets of a package, so two versions of one
# package cannot both be satisfied.
note_conflict() {
  local pkg=$1 version=$2 file=$3 line
  line="$version by $(display "$file")"
  grep -qxF "$line" <<<"${requesters[$pkg]}" || requesters[$pkg]+=$'\n'"$line"
  grep -qxF "$pkg" <<<"$(printf '%s\n' "${conflicted[@]:-}")" || conflicted+=("$pkg")
}

report_conflicts() {
  local pkg
  for pkg in "${conflicted[@]}"; do
    {
      echo "::error::$NAMESPACE:$pkg is required at more than one version:"
      sort -u <<<"${requesters[$pkg]}" | sed 's/^/::error::  /'
      echo "::error::Everything that reaches one package must name the same version of it."
      echo "::error::Repoint whichever should move, or leave them all on the older version."
    } >&2
  done
}

report_decisions() {
  local pkg
  [ "${#required_version[@]}" -eq 0 ] && return 0
  for pkg in $(printf '%s\n' "${!required_version[@]}" | sort); do
    if [ "${resolved_from[$pkg]}" = path ]; then
      echo "  $pkg@${required_version[$pkg]} -> path (wit/$pkg)" >&2
    else
      echo "  $pkg@${required_version[$pkg]} -> registry" >&2
    fi
  done
}

write_wkg_toml() {
  local pkg lines=()
  for pkg in $(printf '%s\n' "${!resolved_from[@]}" | sort); do
    [ "${resolved_from[$pkg]}" = path ] || continue
    lines+=("\"$NAMESPACE:$pkg\" = { path = \"$(realpath --relative-to="$PWD" "$root/wit/$pkg")\" }")
  done

  if [ "$DRY_RUN" = true ]; then
    if [ "${#lines[@]}" -eq 0 ]; then
      echo "# no overrides: every dependency comes from the registry"
    else
      render "${lines[@]}"
    fi
    return 0
  fi

  if [ -e wkg.toml ] && ! generated wkg.toml; then
    echo "::error::generate-wkg-toml.sh: $(display "$PWD")/wkg.toml was not generated by this script." >&2
    echo "::error::Refusing to touch it. Delete it to let the generator take over." >&2
    return 1
  fi

  if [ "${#lines[@]}" -eq 0 ]; then
    rm -f wkg.toml
    return 0
  fi

  render "${lines[@]}" >wkg.toml
}

render() {
  echo "$HEADER"
  echo "# Local when this checkout declares the version asked for, registry otherwise."
  echo
  echo "[overrides]"
  printf '%s\n' "$@"
}

# Match the marker, not the whole HEADER, so files from an earlier script name still count.
generated() {
  head -1 "$1" 2>/dev/null | grep -qE '^# Generated by scripts/'
}

display() {
  realpath --relative-to="$root" "$1" 2>/dev/null || echo "$1"
}

main "$@"
