package betty-blocks:data-api;

interface data-api {
    // use types when it exists
    use betty-blocks:types/actions.{json-string};

    record pending-mutation {
        mutation-name: string,
        mutation: string,
        variables: json-string,
    }

    resource data-api {
        constructor(application-id: string, action-id: string, jwt: option<string>);


        // capture api. Will capture single mutations and when calling apply-capture will apply them all at once.
        // the query and many mutations will just pass through it.

        /// start capturing the mutations
        start-capture: func() -> result<_, string>;
        /// discard the current captured mutations
        discard-capture: func() -> result<string, string>;
        // or flush or commit ?
        /// apply all the captured mutations
        apply-capture: func() -> result<_, string>;

        /// returns the current pending capture, grouped by the order how they need to be applied
        pending-capture: func() -> result<list<list<pending-mutation>>, string>;

        /// do a graphql request to the data-api
        request: func(query: string, variables: json-string) -> result<json-string, string>;

        /// do a graphql request to the data-api, only use when you know what you are doing
        request-raw: func(query: string, variables: json-string) -> result<json-string, string>;
    }

    record helper-context {
        application-id: string,
        action-id: string,
        log-id: string,
        encrypted-configurations: option<list<string>>,
        jwt: option<string>,
    }

    request: func(helper-context: helper-context, query: string, variables: string) -> result<string, string>;
}

world provider {
    export data-api;
}
