name = "http-hello-world"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "fetcher"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:data-api"
source = "file://../../../providers/data-api/wit/world.wit"

[[registry.pull.sources]]
target = "betty-blocks:key-vault/key-vault"
source = "file://../../../providers/key-vault/wit/world.wit"
