name = "http-hello-world"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "component"
wasm_target = "wasm32-wasip2"

[[registry.pull.sources]]
target = "betty-blocks:data-api/data-api"
source = "file://../wit/world.wit"

[[registry.pull.sources]]
target = "data-api:crud/crud"
source = "file://../component/wit/world.wit"
