package betty-blocks-types:pdf-generator@2.0.0;

interface pdf-generator {
    use betty-blocks-types:data-api/data-api@2.0.0.{helper-context};

    generate: func(helper-context: helper-context, html: string) -> result<list<u8>, string>;
}
