apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: smtp-provider
  annotations:
    version: v0.0.1
    description: 'An application to test the smtp provider'
spec:
  components:
    - name: test-component
      type: component
      properties:
        image: file:///tmp/component.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: smtp-provider
            namespace: betty-blocks
            package: smtp
            interfaces: [client]

    - name: smtp-provider
      type: capability
      properties:
        image: file:///tmp/provider.par.gz
        id: smtp-provider

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: test-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000
