package betty-blocks-utilities:crud@2.0.0;

world component {
    import wasi:logging/logging@0.1.0-draft;
    import betty-blocks-types:types/types@2.1.0;
    import betty-blocks-types:data-api/data-api@2.0.0;
    export betty-blocks-types:crud/crud@2.0.0;
}
