package betty-blocks-utilities:crud@3.0.0;

world component {
    import wasi:logging/logging@0.1.0-draft;
    import betty-blocks-types:types/types@3.0.0;
    import betty-blocks-types:data-api/data-api@3.0.0;
    export betty-blocks-types:crud/crud@3.0.0;
}
