name: CI

on:
  pull_request:

jobs:
  mix_test:
    runs-on: ubuntu-24.04
    env:
      MIX_ENV: test
    name: Elixir ${{ matrix.pair.elixir }} / OTP ${{ matrix.pair.otp }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.18.4
              otp: 27.3.4
            lint: lint
          - pair:
              elixir: 1.18.4
              otp: 27.3.4
    steps:
      - uses: actions/checkout@v4
      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Elixir
        uses: actions/cache@v4
        with:
          path: |
            integration-test/_build
            integration-test/deps
          key: ${{ runner.os }}-elixir-${{ hashFiles('mix.lock') }}
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2

      - uses: taiki-e/install-action@v2
        with:
          tool: just,wkg,wash

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - run: just build-providers-integration-test
        if: ${{ !matrix.lint }}

      - name: Install Dependencies
        run: cd integration-test && mix hex.organization auth betty_blocks_bv --key ${{ secrets.HEX_API_KEY }} && mix deps.get

      - run: cd integration-test && mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: cd integration-test && mix deps.compile

      - run: cd integration-test && mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run elixir tests
        run: cd integration-test && mix test
        if: ${{ !matrix.lint }}
